# Generated by Django 6.0.7 on 2026-08-04 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_alter_cita_estado'),
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(max_length=1000)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Kilogramos', max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, help_text='Metros', max_digits=4, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, help_text='Latidos por minuto', null=True)),
                ('saturacion_oxigeno', models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje', null=True)),
                ('diagnostico', models.TextField(max_length=3000)),
                ('tratamiento', models.TextField(max_length=3000)),
                ('observaciones', models.TextField(blank=True, max_length=2000)),
                ('atendida_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historial_clinico', to='citas.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historias clínicas',
                'ordering': ('-atendida_en',),
            },
        ),
    ]
