# Generated by Django 6.0.7 on 2026-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("icono", models.CharField(blank=True, max_length=100)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="servicios/"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("imagen", models.ImageField(upload_to="slider/")),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("comentario", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="testimonios/"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
