# Generated by Django 6.0.7 on 2026-08-04 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_alter_cita_estado'),
        ('historial', '0001_initial'),
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(max_length=3000)),
                ('medicamentos', models.TextField(max_length=3000)),
                ('dosis', models.TextField(max_length=1000)),
                ('frecuencia', models.TextField(max_length=1000)),
                ('duracion', models.CharField(max_length=500)),
                ('indicaciones', models.TextField(max_length=3000)),
                ('observaciones', models.TextField(blank=True, max_length=2000)),
                ('firma_digital', models.CharField(max_length=500)),
                ('codigo_verificacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf', models.FileField(blank=True, upload_to='recetas/%Y/%m/')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=12)),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receta', to='citas.cita')),
                ('historial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receta', to='historial.historialclinico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-emitida_en',),
            },
        ),
    ]
