# Generated by Django 6.0.7 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("usuarios", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("RECEPCIONISTA", "Recepcionista"),
                    ("MEDICO", "Médico"),
                    ("PACIENTE", "Paciente"),
                ],
                default="PACIENTE",
                max_length=20,
            ),
        ),
    ]
